// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: kv_opt.proto
#ifndef GRPC_kv_5fopt_2eproto__INCLUDED
#define GRPC_kv_5fopt_2eproto__INCLUDED

#include "kv_opt.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace kv_operate {

// The KV service definition.
class KV_server final {
 public:
  static constexpr char const* service_full_name() {
    return "kv_operate.KV_server";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Add_KV(::grpc::ClientContext* context, const ::kv_operate::Add_Req& request, ::kv_operate::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>> AsyncAdd_KV(::grpc::ClientContext* context, const ::kv_operate::Add_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>>(AsyncAdd_KVRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>> PrepareAsyncAdd_KV(::grpc::ClientContext* context, const ::kv_operate::Add_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>>(PrepareAsyncAdd_KVRaw(context, request, cq));
    }
    virtual ::grpc::Status Delete_KV(::grpc::ClientContext* context, const ::kv_operate::Delete_Req& request, ::kv_operate::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>> AsyncDelete_KV(::grpc::ClientContext* context, const ::kv_operate::Delete_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>>(AsyncDelete_KVRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>> PrepareAsyncDelete_KV(::grpc::ClientContext* context, const ::kv_operate::Delete_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>>(PrepareAsyncDelete_KVRaw(context, request, cq));
    }
    virtual ::grpc::Status Query_KV(::grpc::ClientContext* context, const ::kv_operate::Query_Req& request, ::kv_operate::Reply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>> AsyncQuery_KV(::grpc::ClientContext* context, const ::kv_operate::Query_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>>(AsyncQuery_KVRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>> PrepareAsyncQuery_KV(::grpc::ClientContext* context, const ::kv_operate::Query_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>>(PrepareAsyncQuery_KVRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Add_KV(::grpc::ClientContext* context, const ::kv_operate::Add_Req* request, ::kv_operate::Reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Add_KV(::grpc::ClientContext* context, const ::kv_operate::Add_Req* request, ::kv_operate::Reply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Delete_KV(::grpc::ClientContext* context, const ::kv_operate::Delete_Req* request, ::kv_operate::Reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Delete_KV(::grpc::ClientContext* context, const ::kv_operate::Delete_Req* request, ::kv_operate::Reply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Query_KV(::grpc::ClientContext* context, const ::kv_operate::Query_Req* request, ::kv_operate::Reply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Query_KV(::grpc::ClientContext* context, const ::kv_operate::Query_Req* request, ::kv_operate::Reply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>* AsyncAdd_KVRaw(::grpc::ClientContext* context, const ::kv_operate::Add_Req& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>* PrepareAsyncAdd_KVRaw(::grpc::ClientContext* context, const ::kv_operate::Add_Req& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>* AsyncDelete_KVRaw(::grpc::ClientContext* context, const ::kv_operate::Delete_Req& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>* PrepareAsyncDelete_KVRaw(::grpc::ClientContext* context, const ::kv_operate::Delete_Req& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>* AsyncQuery_KVRaw(::grpc::ClientContext* context, const ::kv_operate::Query_Req& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::kv_operate::Reply>* PrepareAsyncQuery_KVRaw(::grpc::ClientContext* context, const ::kv_operate::Query_Req& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Add_KV(::grpc::ClientContext* context, const ::kv_operate::Add_Req& request, ::kv_operate::Reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>> AsyncAdd_KV(::grpc::ClientContext* context, const ::kv_operate::Add_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>>(AsyncAdd_KVRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>> PrepareAsyncAdd_KV(::grpc::ClientContext* context, const ::kv_operate::Add_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>>(PrepareAsyncAdd_KVRaw(context, request, cq));
    }
    ::grpc::Status Delete_KV(::grpc::ClientContext* context, const ::kv_operate::Delete_Req& request, ::kv_operate::Reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>> AsyncDelete_KV(::grpc::ClientContext* context, const ::kv_operate::Delete_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>>(AsyncDelete_KVRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>> PrepareAsyncDelete_KV(::grpc::ClientContext* context, const ::kv_operate::Delete_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>>(PrepareAsyncDelete_KVRaw(context, request, cq));
    }
    ::grpc::Status Query_KV(::grpc::ClientContext* context, const ::kv_operate::Query_Req& request, ::kv_operate::Reply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>> AsyncQuery_KV(::grpc::ClientContext* context, const ::kv_operate::Query_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>>(AsyncQuery_KVRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>> PrepareAsyncQuery_KV(::grpc::ClientContext* context, const ::kv_operate::Query_Req& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>>(PrepareAsyncQuery_KVRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Add_KV(::grpc::ClientContext* context, const ::kv_operate::Add_Req* request, ::kv_operate::Reply* response, std::function<void(::grpc::Status)>) override;
      void Add_KV(::grpc::ClientContext* context, const ::kv_operate::Add_Req* request, ::kv_operate::Reply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Delete_KV(::grpc::ClientContext* context, const ::kv_operate::Delete_Req* request, ::kv_operate::Reply* response, std::function<void(::grpc::Status)>) override;
      void Delete_KV(::grpc::ClientContext* context, const ::kv_operate::Delete_Req* request, ::kv_operate::Reply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Query_KV(::grpc::ClientContext* context, const ::kv_operate::Query_Req* request, ::kv_operate::Reply* response, std::function<void(::grpc::Status)>) override;
      void Query_KV(::grpc::ClientContext* context, const ::kv_operate::Query_Req* request, ::kv_operate::Reply* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>* AsyncAdd_KVRaw(::grpc::ClientContext* context, const ::kv_operate::Add_Req& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>* PrepareAsyncAdd_KVRaw(::grpc::ClientContext* context, const ::kv_operate::Add_Req& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>* AsyncDelete_KVRaw(::grpc::ClientContext* context, const ::kv_operate::Delete_Req& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>* PrepareAsyncDelete_KVRaw(::grpc::ClientContext* context, const ::kv_operate::Delete_Req& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>* AsyncQuery_KVRaw(::grpc::ClientContext* context, const ::kv_operate::Query_Req& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::kv_operate::Reply>* PrepareAsyncQuery_KVRaw(::grpc::ClientContext* context, const ::kv_operate::Query_Req& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Add_KV_;
    const ::grpc::internal::RpcMethod rpcmethod_Delete_KV_;
    const ::grpc::internal::RpcMethod rpcmethod_Query_KV_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Add_KV(::grpc::ServerContext* context, const ::kv_operate::Add_Req* request, ::kv_operate::Reply* response);
    virtual ::grpc::Status Delete_KV(::grpc::ServerContext* context, const ::kv_operate::Delete_Req* request, ::kv_operate::Reply* response);
    virtual ::grpc::Status Query_KV(::grpc::ServerContext* context, const ::kv_operate::Query_Req* request, ::kv_operate::Reply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Add_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Add_KV() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Add_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Add_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdd_KV(::grpc::ServerContext* context, ::kv_operate::Add_Req* request, ::grpc::ServerAsyncResponseWriter< ::kv_operate::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Delete_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Delete_KV() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Delete_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Delete_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Delete_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDelete_KV(::grpc::ServerContext* context, ::kv_operate::Delete_Req* request, ::grpc::ServerAsyncResponseWriter< ::kv_operate::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Query_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Query_KV() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Query_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Query_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQuery_KV(::grpc::ServerContext* context, ::kv_operate::Query_Req* request, ::grpc::ServerAsyncResponseWriter< ::kv_operate::Reply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Add_KV<WithAsyncMethod_Delete_KV<WithAsyncMethod_Query_KV<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Add_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Add_KV() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::kv_operate::Add_Req, ::kv_operate::Reply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::kv_operate::Add_Req* request, ::kv_operate::Reply* response) { return this->Add_KV(context, request, response); }));}
    void SetMessageAllocatorFor_Add_KV(
        ::grpc::MessageAllocator< ::kv_operate::Add_Req, ::kv_operate::Reply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::kv_operate::Add_Req, ::kv_operate::Reply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Add_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Add_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Add_KV(
      ::grpc::CallbackServerContext* /*context*/, const ::kv_operate::Add_Req* /*request*/, ::kv_operate::Reply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Delete_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Delete_KV() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::kv_operate::Delete_Req, ::kv_operate::Reply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::kv_operate::Delete_Req* request, ::kv_operate::Reply* response) { return this->Delete_KV(context, request, response); }));}
    void SetMessageAllocatorFor_Delete_KV(
        ::grpc::MessageAllocator< ::kv_operate::Delete_Req, ::kv_operate::Reply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::kv_operate::Delete_Req, ::kv_operate::Reply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Delete_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Delete_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Delete_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Delete_KV(
      ::grpc::CallbackServerContext* /*context*/, const ::kv_operate::Delete_Req* /*request*/, ::kv_operate::Reply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Query_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Query_KV() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::kv_operate::Query_Req, ::kv_operate::Reply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::kv_operate::Query_Req* request, ::kv_operate::Reply* response) { return this->Query_KV(context, request, response); }));}
    void SetMessageAllocatorFor_Query_KV(
        ::grpc::MessageAllocator< ::kv_operate::Query_Req, ::kv_operate::Reply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::kv_operate::Query_Req, ::kv_operate::Reply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Query_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Query_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Query_KV(
      ::grpc::CallbackServerContext* /*context*/, const ::kv_operate::Query_Req* /*request*/, ::kv_operate::Reply* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Add_KV<WithCallbackMethod_Delete_KV<WithCallbackMethod_Query_KV<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Add_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Add_KV() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Add_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Add_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Delete_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Delete_KV() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Delete_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Delete_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Delete_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Query_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Query_KV() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Query_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Query_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Add_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Add_KV() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Add_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Add_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdd_KV(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Delete_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Delete_KV() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Delete_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Delete_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Delete_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDelete_KV(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Query_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Query_KV() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Query_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Query_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestQuery_KV(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Add_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Add_KV() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Add_KV(context, request, response); }));
    }
    ~WithRawCallbackMethod_Add_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Add_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Add_KV(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Delete_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Delete_KV() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Delete_KV(context, request, response); }));
    }
    ~WithRawCallbackMethod_Delete_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Delete_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Delete_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Delete_KV(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Query_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Query_KV() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Query_KV(context, request, response); }));
    }
    ~WithRawCallbackMethod_Query_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Query_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Query_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Query_KV(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Add_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Add_KV() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::kv_operate::Add_Req, ::kv_operate::Reply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::kv_operate::Add_Req, ::kv_operate::Reply>* streamer) {
                       return this->StreamedAdd_KV(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Add_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Add_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Add_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAdd_KV(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::kv_operate::Add_Req,::kv_operate::Reply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Delete_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Delete_KV() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::kv_operate::Delete_Req, ::kv_operate::Reply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::kv_operate::Delete_Req, ::kv_operate::Reply>* streamer) {
                       return this->StreamedDelete_KV(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Delete_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Delete_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Delete_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDelete_KV(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::kv_operate::Delete_Req,::kv_operate::Reply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Query_KV : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Query_KV() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::kv_operate::Query_Req, ::kv_operate::Reply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::kv_operate::Query_Req, ::kv_operate::Reply>* streamer) {
                       return this->StreamedQuery_KV(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Query_KV() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Query_KV(::grpc::ServerContext* /*context*/, const ::kv_operate::Query_Req* /*request*/, ::kv_operate::Reply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedQuery_KV(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::kv_operate::Query_Req,::kv_operate::Reply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Add_KV<WithStreamedUnaryMethod_Delete_KV<WithStreamedUnaryMethod_Query_KV<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Add_KV<WithStreamedUnaryMethod_Delete_KV<WithStreamedUnaryMethod_Query_KV<Service > > > StreamedService;
};

}  // namespace kv_operate


#endif  // GRPC_kv_5fopt_2eproto__INCLUDED
