// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: kv_opt.proto

#include "kv_opt.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace kv_operate {
        template <typename>
PROTOBUF_CONSTEXPR Add_Req::Add_Req(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.kv_json_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct Add_ReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Add_ReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Add_ReqDefaultTypeInternal() {}
  union {
    Add_Req _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Add_ReqDefaultTypeInternal _Add_Req_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR Delete_Req::Delete_Req(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.key_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct Delete_ReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Delete_ReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Delete_ReqDefaultTypeInternal() {}
  union {
    Delete_Req _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Delete_ReqDefaultTypeInternal _Delete_Req_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR Query_Req::Query_Req(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.key_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct Query_ReqDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Query_ReqDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Query_ReqDefaultTypeInternal() {}
  union {
    Query_Req _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Query_ReqDefaultTypeInternal _Query_Req_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR Reply::Reply(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.res_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct ReplyDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ReplyDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ReplyDefaultTypeInternal() {}
  union {
    Reply _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ReplyDefaultTypeInternal _Reply_default_instance_;
}  // namespace kv_operate
static ::_pb::Metadata file_level_metadata_kv_5fopt_2eproto[4];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_kv_5fopt_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_kv_5fopt_2eproto = nullptr;
const ::uint32_t TableStruct_kv_5fopt_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::kv_operate::Add_Req, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::kv_operate::Add_Req, _impl_.kv_json_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::kv_operate::Delete_Req, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::kv_operate::Delete_Req, _impl_.key_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::kv_operate::Query_Req, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::kv_operate::Query_Req, _impl_.key_),
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::kv_operate::Reply, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::kv_operate::Reply, _impl_.res_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::kv_operate::Add_Req)},
        {9, -1, -1, sizeof(::kv_operate::Delete_Req)},
        {18, -1, -1, sizeof(::kv_operate::Query_Req)},
        {27, -1, -1, sizeof(::kv_operate::Reply)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::kv_operate::_Add_Req_default_instance_._instance,
    &::kv_operate::_Delete_Req_default_instance_._instance,
    &::kv_operate::_Query_Req_default_instance_._instance,
    &::kv_operate::_Reply_default_instance_._instance,
};
const char descriptor_table_protodef_kv_5fopt_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\014kv_opt.proto\022\nkv_operate\"\032\n\007Add_Req\022\017\n"
    "\007kv_json\030\001 \001(\t\"\031\n\nDelete_Req\022\013\n\003key\030\001 \001("
    "\t\"\030\n\tQuery_Req\022\013\n\003key\030\001 \001(\t\"\024\n\005Reply\022\013\n\003"
    "res\030\001 \001(\t2\261\001\n\tKV_server\0222\n\006Add_KV\022\023.kv_o"
    "perate.Add_Req\032\021.kv_operate.Reply\"\000\0228\n\tD"
    "elete_KV\022\026.kv_operate.Delete_Req\032\021.kv_op"
    "erate.Reply\"\000\0226\n\010Query_KV\022\025.kv_operate.Q"
    "uery_Req\032\021.kv_operate.Reply\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_kv_5fopt_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_kv_5fopt_2eproto = {
    false,
    false,
    317,
    descriptor_table_protodef_kv_5fopt_2eproto,
    "kv_opt.proto",
    &descriptor_table_kv_5fopt_2eproto_once,
    nullptr,
    0,
    4,
    schemas,
    file_default_instances,
    TableStruct_kv_5fopt_2eproto::offsets,
    file_level_metadata_kv_5fopt_2eproto,
    file_level_enum_descriptors_kv_5fopt_2eproto,
    file_level_service_descriptors_kv_5fopt_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_kv_5fopt_2eproto_getter() {
  return &descriptor_table_kv_5fopt_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_kv_5fopt_2eproto(&descriptor_table_kv_5fopt_2eproto);
namespace kv_operate {
// ===================================================================

class Add_Req::_Internal {
 public:
};

Add_Req::Add_Req(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kv_operate.Add_Req)
}
Add_Req::Add_Req(const Add_Req& from) : ::google::protobuf::Message() {
  Add_Req* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.kv_json_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.kv_json_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.kv_json_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_kv_json().empty()) {
    _this->_impl_.kv_json_.Set(from._internal_kv_json(), _this->GetArenaForAllocation());
  }

  // @@protoc_insertion_point(copy_constructor:kv_operate.Add_Req)
}
inline void Add_Req::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.kv_json_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _impl_.kv_json_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.kv_json_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
Add_Req::~Add_Req() {
  // @@protoc_insertion_point(destructor:kv_operate.Add_Req)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Add_Req::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.kv_json_.Destroy();
}
void Add_Req::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void Add_Req::Clear() {
// @@protoc_insertion_point(message_clear_start:kv_operate.Add_Req)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.kv_json_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Add_Req::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 34, 2> Add_Req::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Add_Req_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string kv_json = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Add_Req, _impl_.kv_json_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string kv_json = 1;
    {PROTOBUF_FIELD_OFFSET(Add_Req, _impl_.kv_json_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\22\7\0\0\0\0\0\0"
    "kv_operate.Add_Req"
    "kv_json"
  }},
};

::uint8_t* Add_Req::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kv_operate.Add_Req)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string kv_json = 1;
  if (!this->_internal_kv_json().empty()) {
    const std::string& _s = this->_internal_kv_json();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kv_operate.Add_Req.kv_json");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kv_operate.Add_Req)
  return target;
}

::size_t Add_Req::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kv_operate.Add_Req)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string kv_json = 1;
  if (!this->_internal_kv_json().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_kv_json());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Add_Req::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    Add_Req::MergeImpl
};
const ::google::protobuf::Message::ClassData*Add_Req::GetClassData() const { return &_class_data_; }


void Add_Req::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Add_Req*>(&to_msg);
  auto& from = static_cast<const Add_Req&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kv_operate.Add_Req)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_kv_json().empty()) {
    _this->_internal_set_kv_json(from._internal_kv_json());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Add_Req::CopyFrom(const Add_Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kv_operate.Add_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Add_Req::IsInitialized() const {
  return true;
}

void Add_Req::InternalSwap(Add_Req* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.kv_json_, lhs_arena,
                                       &other->_impl_.kv_json_, rhs_arena);
}

::google::protobuf::Metadata Add_Req::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_kv_5fopt_2eproto_getter, &descriptor_table_kv_5fopt_2eproto_once,
      file_level_metadata_kv_5fopt_2eproto[0]);
}
// ===================================================================

class Delete_Req::_Internal {
 public:
};

Delete_Req::Delete_Req(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kv_operate.Delete_Req)
}
Delete_Req::Delete_Req(const Delete_Req& from) : ::google::protobuf::Message() {
  Delete_Req* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.key_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_key().empty()) {
    _this->_impl_.key_.Set(from._internal_key(), _this->GetArenaForAllocation());
  }

  // @@protoc_insertion_point(copy_constructor:kv_operate.Delete_Req)
}
inline void Delete_Req::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.key_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
Delete_Req::~Delete_Req() {
  // @@protoc_insertion_point(destructor:kv_operate.Delete_Req)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Delete_Req::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.key_.Destroy();
}
void Delete_Req::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void Delete_Req::Clear() {
// @@protoc_insertion_point(message_clear_start:kv_operate.Delete_Req)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.key_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Delete_Req::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 33, 2> Delete_Req::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Delete_Req_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Delete_Req, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(Delete_Req, _impl_.key_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\3\0\0\0\0\0\0"
    "kv_operate.Delete_Req"
    "key"
  }},
};

::uint8_t* Delete_Req::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kv_operate.Delete_Req)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    const std::string& _s = this->_internal_key();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kv_operate.Delete_Req.key");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kv_operate.Delete_Req)
  return target;
}

::size_t Delete_Req::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kv_operate.Delete_Req)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_key());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Delete_Req::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    Delete_Req::MergeImpl
};
const ::google::protobuf::Message::ClassData*Delete_Req::GetClassData() const { return &_class_data_; }


void Delete_Req::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Delete_Req*>(&to_msg);
  auto& from = static_cast<const Delete_Req&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kv_operate.Delete_Req)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Delete_Req::CopyFrom(const Delete_Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kv_operate.Delete_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Delete_Req::IsInitialized() const {
  return true;
}

void Delete_Req::InternalSwap(Delete_Req* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, lhs_arena,
                                       &other->_impl_.key_, rhs_arena);
}

::google::protobuf::Metadata Delete_Req::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_kv_5fopt_2eproto_getter, &descriptor_table_kv_5fopt_2eproto_once,
      file_level_metadata_kv_5fopt_2eproto[1]);
}
// ===================================================================

class Query_Req::_Internal {
 public:
};

Query_Req::Query_Req(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kv_operate.Query_Req)
}
Query_Req::Query_Req(const Query_Req& from) : ::google::protobuf::Message() {
  Query_Req* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.key_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_key().empty()) {
    _this->_impl_.key_.Set(from._internal_key(), _this->GetArenaForAllocation());
  }

  // @@protoc_insertion_point(copy_constructor:kv_operate.Query_Req)
}
inline void Query_Req::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.key_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _impl_.key_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.key_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
Query_Req::~Query_Req() {
  // @@protoc_insertion_point(destructor:kv_operate.Query_Req)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Query_Req::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.key_.Destroy();
}
void Query_Req::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void Query_Req::Clear() {
// @@protoc_insertion_point(message_clear_start:kv_operate.Query_Req)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.key_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Query_Req::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 32, 2> Query_Req::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Query_Req_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string key = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Query_Req, _impl_.key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string key = 1;
    {PROTOBUF_FIELD_OFFSET(Query_Req, _impl_.key_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\24\3\0\0\0\0\0\0"
    "kv_operate.Query_Req"
    "key"
  }},
};

::uint8_t* Query_Req::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kv_operate.Query_Req)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    const std::string& _s = this->_internal_key();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kv_operate.Query_Req.key");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kv_operate.Query_Req)
  return target;
}

::size_t Query_Req::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kv_operate.Query_Req)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string key = 1;
  if (!this->_internal_key().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_key());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Query_Req::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    Query_Req::MergeImpl
};
const ::google::protobuf::Message::ClassData*Query_Req::GetClassData() const { return &_class_data_; }


void Query_Req::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Query_Req*>(&to_msg);
  auto& from = static_cast<const Query_Req&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kv_operate.Query_Req)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_key().empty()) {
    _this->_internal_set_key(from._internal_key());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Query_Req::CopyFrom(const Query_Req& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kv_operate.Query_Req)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Query_Req::IsInitialized() const {
  return true;
}

void Query_Req::InternalSwap(Query_Req* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.key_, lhs_arena,
                                       &other->_impl_.key_, rhs_arena);
}

::google::protobuf::Metadata Query_Req::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_kv_5fopt_2eproto_getter, &descriptor_table_kv_5fopt_2eproto_once,
      file_level_metadata_kv_5fopt_2eproto[2]);
}
// ===================================================================

class Reply::_Internal {
 public:
};

Reply::Reply(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:kv_operate.Reply)
}
Reply::Reply(const Reply& from) : ::google::protobuf::Message() {
  Reply* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.res_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.res_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.res_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_res().empty()) {
    _this->_impl_.res_.Set(from._internal_res(), _this->GetArenaForAllocation());
  }

  // @@protoc_insertion_point(copy_constructor:kv_operate.Reply)
}
inline void Reply::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.res_){},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _impl_.res_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.res_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
Reply::~Reply() {
  // @@protoc_insertion_point(destructor:kv_operate.Reply)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Reply::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.res_.Destroy();
}
void Reply::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void Reply::Clear() {
// @@protoc_insertion_point(message_clear_start:kv_operate.Reply)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.res_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Reply::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 28, 2> Reply::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Reply_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // string res = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Reply, _impl_.res_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string res = 1;
    {PROTOBUF_FIELD_OFFSET(Reply, _impl_.res_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\3\0\0\0\0\0\0"
    "kv_operate.Reply"
    "res"
  }},
};

::uint8_t* Reply::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:kv_operate.Reply)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string res = 1;
  if (!this->_internal_res().empty()) {
    const std::string& _s = this->_internal_res();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "kv_operate.Reply.res");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:kv_operate.Reply)
  return target;
}

::size_t Reply::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:kv_operate.Reply)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string res = 1;
  if (!this->_internal_res().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_res());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Reply::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    Reply::MergeImpl
};
const ::google::protobuf::Message::ClassData*Reply::GetClassData() const { return &_class_data_; }


void Reply::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Reply*>(&to_msg);
  auto& from = static_cast<const Reply&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:kv_operate.Reply)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_res().empty()) {
    _this->_internal_set_res(from._internal_res());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Reply::CopyFrom(const Reply& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:kv_operate.Reply)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Reply::IsInitialized() const {
  return true;
}

void Reply::InternalSwap(Reply* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.res_, lhs_arena,
                                       &other->_impl_.res_, rhs_arena);
}

::google::protobuf::Metadata Reply::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_kv_5fopt_2eproto_getter, &descriptor_table_kv_5fopt_2eproto_once,
      file_level_metadata_kv_5fopt_2eproto[3]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace kv_operate
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
